INSERT INTO tasks (task, is_completed, created_at, updated_at) VALUES
('タスク1', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('タスク2', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('タスク3', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('タスク4', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('タスク5', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);